In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# 1) Configuración de la conexión mediante el motor (engine) usando SQLAlchemy:
USER = "root"
PASSWORD = "yes"
HOST = "localhost"
DATABASE = "motogp_db"

connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}/{DATABASE}"
engine = create_engine(connection_string)

print("Conexión configurada con éxito.")

Conexión configurada con éxito.

In [4]:
# 2) Leer el CSV:
df = pd.read_csv("../data/moto_results.csv")
df.head(1)

,year,sequence,category,rider_first_name,rider_last_name,rider_number,rider_country,team_name,bike,position,points,speed,time,race_name,circuit_name,circuit_country,date
0,2021,16,Moto2,Fermín,Aldeguer,54.0,SPA,+EGO Speed Up,Boscoscuro,16,0,154.4,+37.590,Gran Premio Nolan Del Made In Italy E Dell'Emi...,Misano World Circuit Marco Simoncelli,IT,2021-10-24

In [7]:
# 3) Extraer países únicos para la tabla 'countries':
# Usamos 'rider_country' como fuente para id_country:
countries = df[['rider_country']].drop_duplicates().dropna()
countries.columns = ['id_country']

countries.head(3)

  id_country
0        SPA
1        ITA
2        NED